workflows:
  android-build:
    name: Android Debug Build
    instance_type: mac_mini_m2

    environment:
      java: 11

    scripts:
      - name: Find Module Name
        script: |
          # هذا الأمر سيطبع قائمة بكل الوحدات (المشاريع الفرعية)
          gradle projects
          
    # تم حذف قسم artifacts مؤقتاً لأننا لن ننتج APK
